### ISSUE TITLE
Page didn't re-generate correctly

### ISSUE THREAD

**Issue by wkoszek** [OSVTAC/OSVTAC.github.io#1]
Go to: https://osvtac.github.io

I click: "Open Source Voting System Project Recommendations"

I get directed to https://osvtac.github.io/recommendations/index and I get an error 404.

**Comment by cjerdonek** [comment]
Thanks for the notice. Hmm, that's weird. GitHub Pages didn't show there was an error in building, etc, when I last pushed. I re-pushed, and it seems to be working now. Can you try again?

**Comment by wkoszek** [comment]
@cjerdonek This works now. Thanks.

**Comment by cjerdonek** [comment]
Okay, great. Thanks again for reporting!

**Comment by cjerdonek** [comment]
FYI, for the record, I just heard back from GH support, and they confirmed to me that there was in fact "unscheduled maintenance yesterday that caused all builds of sites with submodule dependencies to fail." So that explains it..

**Comment by wkoszek** [comment]
Thanks for double-checking.
