### ISSUE TITLE
[not website] Audio from April 12 meeting recorded with mono audio

### ISSUE THREAD

**Issue by wkoszek** [OSVTAC/OSVTAC.github.io#2]
Looks like only "left" audio channel is recorded. The right audio channel isn't present.

Previous recordings were fine.

**Comment by cjerdonek** [comment]
Thanks. I'll take a look and see if this can be fixed within the next few days.

**Comment by wkoszek** [comment]
@cjerdonek Thanks.

For people reading this: if you're listening on a macOS through the headphones, you may help yourself by going to: Apple Menu -> Settings -> Accessibility -> Play stereo audio as mono
